name: Move Issue to "In Progress" on PR Creation

on:
  pull_request:
    types:
      - opened

jobs:
  move-to-in-progress:
    runs-on: ubuntu-latest
    steps:
      - name: Move linked issue to In Progress
        uses: peter-evans/link-and-close-issues@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          project-url: https://github.com/orgs/TON-ORGANISATION/projects/1
          status: "In Progress"

